minimumReleaseAge: 1440

onlyBuiltDependencies:
  - cypress
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  esbuild@<=0.24.2: ">=0.27.1"
  qs@<6.14.1: ">=6.14.1"
  systeminformation@<5.27.14: ">=5.27.14"
